---
- name: Remove label on GCE instance
  community.google.gce_labels:
    resource_url: "{{ hostvars[inventory_hostname]['selfLink'] }}"
    labels:
      ansible_configured: "false"
    project_id: "{{ project }}"
    state: absent
  delegate_to: localhost

- name: Add label on GCE instance
  community.google.gce_labels:
    resource_url: "{{ hostvars[inventory_hostname]['selfLink'] }}"
    labels:
      ansible_configured: "true"
    project_id: "{{ project }}"
    state: present
  delegate_to: localhost
