name: Run Ansible

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      github-runner:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  run-ansible:
    runs-on: ${{ inputs.github-runner }}
    environment: ${{ inputs.environment }}
    env:
      ANSIBLE_INVENTORY_PLUGINS: $HOME/.ansible/plugins/inventory

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Ansible
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          source $HOME/.ansible_venv/bin/activate
          ansible-config dump --only-changed
          ansible-inventory -i inventories/"${{ inputs.environment }}".yml --list
        shell: bash
