name: Configure VMs

on:
  workflow_dispatch:  # This allows the workflow to be triggered by the API
  pull_request:
    branches: [main]

jobs:
  configure:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/ansible.yml
    with:
      environment: testing
      github-runner: self-hosted
      ansible-user: ansible
      runner-user: github-runner
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }} 