name: Configure Testing VMs

on:
  workflow_dispatch:  # This allows the workflow to be triggered by the API

jobs:
  configure:
    uses: ./.github/workflows/ansible.yml
    with:
      environment: testing
      github-runner: ansible 
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
